package com.model;
// Generated Aug 23, 2012 11:13:54 AM by Hibernate Tools 3.2.1.GA

import org.springframework.web.multipart.commons.CommonsMultipartFile;




/**
 * Filedatabase generated by hbm2java
 */
public class Filedatabase  implements java.io.Serializable {


     private String userName;
     private String courseId;
     private String fileName;
     private Long fileSize;
     private String fileType;
     private String fileLocation;
     private String fileId;
     private CommonsMultipartFile fileData;

    public CommonsMultipartFile getFileData() {
        return fileData;
    }

    public void setFileData(CommonsMultipartFile fileData) {
        this.fileData = fileData;
    }
    public Filedatabase() {
    }

	
    public Filedatabase(String userName) {
        this.userName = userName;
    }
    public Filedatabase(String userName, String courseId, String fileName, Long fileSize, String fileType, String fileLocation, String fileId) {
       this.userName = userName;
       this.courseId = courseId;
       this.fileName = fileName;
       this.fileSize = fileSize;
       this.fileType = fileType;
       this.fileLocation = fileLocation;
       this.fileId = fileId;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Long getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    public String getFileLocation() {
        return this.fileLocation;
    }
    
    public void setFileLocation(String fileLocation) {
        this.fileLocation = fileLocation;
    }
    public String getFileId() {
        return this.fileId;
    }
    
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }




}


