package com.model;
// Generated Aug 20, 2012 8:44:26 PM by Hibernate Tools 3.2.1.GA

import org.springframework.web.multipart.commons.CommonsMultipartFile;




/**
 * Studentfile generated by hbm2java
 */
public class Studentfile  implements java.io.Serializable {


     private String studentId;
     private String name;
     private String department;
     private Integer semester;
     private String address;
     private String email;
     private String telephone;
     private String picture;
     private String userName;
     private String password;
     private Long fileSize;
     private String fileName;
     private String fileType;
     private String room;
     private CommonsMultipartFile fileData;

    public CommonsMultipartFile getFileData() {
        return fileData;
    }

    public void setFileData(CommonsMultipartFile fileData) {
        this.fileData = fileData;
    }
    public Studentfile() {
    }

	
    public Studentfile(String studentId) {
        this.studentId = studentId;
    }
    public Studentfile(String studentId, String name, String department, Integer semester, String address, String email, String telephone, String picture, String userName, String password, Long fileSize, String fileName, String fileType, String room) {
       this.studentId = studentId;
       this.name = name;
       this.department = department;
       this.semester = semester;
       this.address = address;
       this.email = email;
       this.telephone = telephone;
       this.picture = picture;
       this.userName = userName;
       this.password = password;
       this.fileSize = fileSize;
       this.fileName = fileName;
       this.fileType = fileType;
       this.room = room;
    }
   
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public Integer getSemester() {
        return this.semester;
    }
    
    public void setSemester(Integer semester) {
        this.semester = semester;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Long getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }




}


