package com.model;
// Generated Aug 23, 2012 11:13:37 AM by Hibernate Tools 3.2.1.GA

import org.springframework.web.multipart.commons.CommonsMultipartFile;




/**
 * Teacherfile generated by hbm2java
 */
public class Teacherfile  implements java.io.Serializable {


     private String userName;
     private String password;
     private String name;
     private String department;
     private String designation;
     private String address;
     private String email;
     private String telephone;
     private String office;
     private String picture;
     private String fileName;
     private Long fileSize;
     private String fileType;
      private CommonsMultipartFile fileData;

    public CommonsMultipartFile getFileData() {
        return fileData;
    }

    public void setFileData(CommonsMultipartFile fileData) {
        this.fileData = fileData;
    }
    public Teacherfile() {
    }

	
    public Teacherfile(String userName) {
        this.userName = userName;
    }
    public Teacherfile(String userName, String password, String name, String department, String designation, String address, String email, String telephone, String office, String picture, String fileName, Long fileSize, String fileType) {
       this.userName = userName;
       this.password = password;
       this.name = name;
       this.department = department;
       this.designation = designation;
       this.address = address;
       this.email = email;
       this.telephone = telephone;
       this.office = office;
       this.picture = picture;
       this.fileName = fileName;
       this.fileSize = fileSize;
       this.fileType = fileType;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getOffice() {
        return this.office;
    }
    
    public void setOffice(String office) {
        this.office = office;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Long getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }




}


