package com.model;
// Generated Aug 23, 2012 11:13:37 AM by Hibernate Tools 3.2.1.GA



/**
 * Teacherauthentication generated by hbm2java
 */
public class Teacherauthentication  implements java.io.Serializable {


     private String userName;
     private String password;
     private String pin;

    public Teacherauthentication() {
    }

	
    public Teacherauthentication(String userName) {
        this.userName = userName;
    }
    public Teacherauthentication(String userName, String password, String pin) {
       this.userName = userName;
       this.password = password;
       this.pin = pin;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }




}


